// Basic Flutter smoke test generated by `flutter create`, updated for this app.

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:remote_support/main.dart';
import 'package:remote_support/providers.dart';

import 'utils/fake_support_auth.dart';

void main() {
  testWidgets('App launches to role selection', (WidgetTester tester) async {
    await tester.pumpWidget(
      ProviderScope(
        overrides: [supportAuthProvider.overrideWithValue(FakeSupportAuth())],
        child: const RemoteSupportApp(),
      ),
    );
    expect(find.text('Remote Support'), findsOneWidget);
    expect(find.text('I need help'), findsOneWidget);
    expect(find.text("I'm support"), findsOneWidget);
  });
}
