"""add_rate_limits"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e1916822e0ee'
down_revision: str | None = '20260818_0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    op.create_index('ix_rate_limits_window', 'rate_limits', ['window_start'], unique=False)
    op.drop_constraint(
        op.f('session_participants_session_id_role_key'),
        'session_participants',
        type_='unique',
    )
    op.create_index(
        'ux_participants_session_role',
        'session_participants',
        ['session_id', 'role'],
        unique=True,
    )
    op.drop_constraint(
        op.f('transcript_utterances_session_id_client_utterance_id_key'),
        'transcript_utterances',
        type_='unique',
    )
    op.create_index(
        'ux_utterance_idem',
        'transcript_utterances',
        ['session_id', 'client_utterance_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_utterance_idem', table_name='transcript_utterances')
    op.create_unique_constraint(
        op.f('transcript_utterances_session_id_client_utterance_id_key'),
        'transcript_utterances',
        ['session_id', 'client_utterance_id'],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index('ux_participants_session_role', table_name='session_participants')
    op.create_unique_constraint(
        op.f('session_participants_session_id_role_key'),
        'session_participants',
        ['session_id', 'role'],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index('ix_rate_limits_window', table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
